name: better_auth_dart
description: A Dart port of better-auth authentication system
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0
  http: ^1.1.0
  pointycastle: ^4.0.0
  lints: ^6.0.0
  thirds: ^0.2.0-alpha.1
